// <auto-generated />
using Foundation.CustomForm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Foundation.CustomForms.Migrations
{
    [DbContext(typeof(CustomFormDbContext))]
    [Migration("20190614033418_type")]
    partial class type
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Foundation.CustomForm.CustomForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FieldGroups");

                    b.Property<string>("Label");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("CustomForms");
                });
#pragma warning restore 612, 618
        }
    }
}
