export default {
    login: "account/login",
    logout: "account/logout",
    setting: "setting",
    apartmentDropdown: "apartment/select-list",
    roomTypeDropdown: "apartment/{id}/room-type-list",
    roomChart: "apartment/chart/room",
    deleteTrace: "consulting/trace",
    addToFavorite: "consulting/favorite",
    removeMyFavorite: "consulting/favorite/remove",
    consultingStatus: "consulting/status",
    transferConsulting: "consulting/transfer",
    transferMultipleConsulting: "consulting/transfer-multiple",
    favoriteCategories: "user/favorite-categories",
    favoriteConsulting: "user/favorite-consulting",
    usersToBeTransfer: "user/transfer",
    workflowList: "workflow/select-list",
    workflow: "workflow",
    usersForWorkflow: "user/workflow-list",
    role: "role",
    company: "company",
    customer: "customer",
    customerFamily: "customer/family",
    user: "user",
    currentUser: "user/current",
    contract: "contract",
    consultingTraces: "consulting-trace/query",
    myApartments: "user/me/apartments",
    workflowStatus: "workFlow/status",
    roomChangeDetails: "contract/room-change",
    servicePackChangeDetails: "contract/service-pack-change",
    appreciationService: "appreciation-service",
    apartment: "apartment",
    consumable: "consumable",
    valueAddedService:"value-added-service"
};
