// <auto-generated />
using Example.Applications.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Example.Applications.Domain.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    [Migration("20190716041825_init123")]
    partial class init123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Example.Applications.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnName("age");

                    b.Property<string>("IdCard")
                        .HasColumnName("id_card");

                    b.Property<string>("Mobile")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnName("photo");

                    b.Property<string>("Source")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers");
                });
#pragma warning restore 612, 618
        }
    }
}
